# Python basics 03:class
working with packages --> numpy and pythonic code
If you have problems running or installing packages (pip not recognized)
https://www.dataquest.io/blog/install-pip-windows/

--> get-pip.py file

In [ ]:
! pip install numpy

In [10]:
import numpy
numpy.version

<module 'numpy.version' from 'c:\\Python312\\Lib\\site-packages\\numpy\\version.py'>

## Import Numpy

In [3]:
import numpy
import numpy as np
from numpy import arange

## Creating arrays
array elements must have the same type

In [24]:
import numpy as np
list = [1,5,8,10,3]
print(list)

array = np.array(list)
print(array)

#list --> treated as a whole and is completely added twice if you multiply
#array --> treats each element and multiplies each element separately.

print(list * 2)
print(array * 2)

list.append(2)
#array.append(2) --> array has fixed size after transformation

#1D arrays
print(np.arange(10)) #evenly spaced intervals with given key, without upperbound
print(np.zeros(10)) #array of x amount of 0's
print(np.ones(10)) #array of x amoutn of 1's

print(np.full(10,5)) #array of given size filled with given number
print(np.random.randint(-5,6,10)) #random array filled with random integers, given low bound, high bound and size

print(np.random.random(10)) #random floats in array of size x

[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[-1 -5  4  2  4 -1  2 -5  1 -4]
[0.42893472 0.09036762 0.72372737 0.85599073 0.85699418 0.1080565
 0.19826996 0.22561542 0.11575164 0.9773528 ]


### Reshaping & converting arrays

In [44]:
import numpy as np

#change array again
array = np.random.randint(-5,6,10)
print(array)

print(array.shape) #display size of array / elements of dimensions
print(array.ndim) #returns number of dimensions

print(array.dtype) #shows the datatype

#i = integer / b = boolean / f = float / M = datetime / S = string
#--> wording also works str int bool ...
array_float = array.astype('f')
print(array_float)

array_string = array.astype(str)
print(array_string)

array_2D = np.reshape(array,(2,5))
print(array_2D)
print(array_2D.ndim) #2
print(array_2D.shape) #(2,5)

array_2D = np.reshape(array,(5,2))
print(array_2D)
#needs a perfect fit --> 10 elements cannot be split into (3,3)
#valueError: cannot reshape array of size 10 into shape (3,3)

array_2D = np.sort(array_2D)
print(array_2D)

print(np.max(array_2D))


[-4  4  2 -1 -2 -4  2  5 -3  4]
(10,)
1
int32
[-4.  4.  2. -1. -2. -4.  2.  5. -3.  4.]
['-4' '4' '2' '-1' '-2' '-4' '2' '5' '-3' '4']
[[-4  4  2 -1 -2]
 [-4  2  5 -3  4]]
2
(2, 5)
[[-4  4]
 [ 2 -1]
 [-2 -4]
 [ 2  5]
 [-3  4]]
[[-4  4]
 [-1  2]
 [-4 -2]
 [ 2  5]
 [-3  4]]
5


## Slicing arrays
[start:end:step]
- start: starting index
- end: last number in line (1 beyond index)
- step: stepsize

In [66]:
import numpy as np
array = np.array([6,2,8,9,3,1,4,7,0,5])
print(array)

print(array[1:5:1]) #[2 8 9 3]
#default step is always 1
print(array[1:5:]) #[2 8 9 3]
print(array[1:5:2]) #[2 9]

#default start is always 0
print(array[0:5:1]) #[6 2 8 9 3]
print(array[:5:1]) #[6 2 8 9 3]

#default end is always the end of the array
print(array[0::1]) #[6 2 8 9 3 1 4 7 0 5]
print(array[0:10:1]) #[6 2 8 9 3 1 4 7 0 5]

#reverse array
print(array[::-1]) #[5 0 7 4 1 3 9 8 2 6]
print(array[10::-1]) #[5 0 7 4 1 3 9 8 2 6]

print(array[0:10:-1]) #doesn't work, because there's no (negative) indexes

print(array[::2]) #[6 8 3 4 0]
print(array[::-2]) #[5 7 1 9 2]

[6 2 8 9 3 1 4 7 0 5]
[2 8 9 3]
[2 8 9 3]
[2 9]
[6 2 8 9 3]
[6 2 8 9 3]
[6 2 8 9 3 1 4 7 0 5]
[6 2 8 9 3 1 4 7 0 5]
[5 0 7 4 1 3 9 8 2 6]
[5 0 7 4 1 3 9 8 2 6]
[]
[6 8 3 4 0]
[5 7 1 9 2]


## working with arrays

In [83]:
import numpy as np

a = np.arange(0,10) #[0 1 2 3 4 5 6 7 8 9]
b = np.arange(9,-1,-1) #[9 8 7 6 5 4 3 2 1 0]
print(a,b)

print(a+b) #[9 9 9 9 9 9 9 9 9 9]
print(a-b) #[-9 -7 -5 -3 -1  1  3  5  7  9]
print(a*b) #[ 0  8 14 18 20 20 18 14  8  0]

print(np.where(a % 2 == 0, a + 1, a)) #if condition --> where(condition,x,y) --> if condition true, return x, return y
print(np.where(b>5)) #you get indexes back
print(np.where(b>5, b, 0)) #if true return number else 0
print()

b = np.reshape(b,(2,5))
print(b)
print()

print(b.sum(axis=0)) #count up columns
print(b.sum(axis=1)) #count up rows
print(b.cumsum(axis=1)) #sum of all elements in row --> sum at current point is printed

print()
print(a.sum()) #calculated sum regardless of size and dimensions
print(b.sum())
print(a.min())
print(a.max())
print(np.sqrt(a)) #square root of every number returned as an array
print(np.sqrt(a.max())) #square root of highest number in array, returned as a float

[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[1 1 3 3 5 5 7 7 9 9]
(array([0, 1, 2, 3]),)
[9 8 7 6 0 0 0 0 0 0]

[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[35 10]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]

45
45
0
9
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3.0


### Exercise: It's magic
Read in a 1D array and a number of rows! Convert the array to 2D! Calculate the sum of each column and if all
the sums are equal --> "It's magic time and you are dealing with a magic table" OR "MAGIC TABLE"

<b>input</b><br>
2 7 0 8 4 1 1 0 10 <br>
3<br>
<b>output</b><br>
True
<pre>
2 7 0
8 4 1
1 0 10
<i>11 11 11</i> --> MAGIC TABLE
</pre>

In [89]:
import numpy as np
s = input()
array1D = np.array(s.split(" "))
array1D = array1D.astype('i')

rows = int(input())
array1D = np.reshape(array1D,(rows,rows))
print(array1D)

sums = np.sum(array1D,axis=0) #0 is cols, 1 is rows
print(sums)

total = np.sum(sums)
if total / rows == sums[0]:
    print("MAGIC TABLE")
else:
    print("NO MAGIC TABLE")


#another approach
check = True
for value in sums: #[11 11 11]
    if value != sums[0]:
        check = False
        break

if check is True:
    print("MAGIC TABLE")
else:
    print("NO MAGIC TABLE")

[[ 2  7  0]
 [ 8  4  1]
 [ 1  0 10]]
[11 11 11]
MAGIC TABLE
